"""Reviewer workspace graph-diff / proof-path preview, per
rabbitqa_spec_v1.0.0.md §6.4: "A graph-diff / proof-path preview for any
GraphChangeSet awaiting approval, generated by calling §5.6 before the approval
action is enabled."

CLI implementation. Calls the real §5.6 handler (validate_changeset_handler) —
never a separate, UI-only recomputation — and gates the approval action on that
call having actually happened in this session, mirroring the §6.3 pattern.
"""

from __future__ import annotations

from compliance_graph.src.api.changesets import validate_changeset_handler


class ApprovalWithoutPreviewError(Exception):
    """§6.4: approval MUST NOT be enabled for a changeset whose graph-diff/
    proof-path preview (i.e. a §5.6 validate call) hasn't happened in this
    session."""


def render_graph_diff_preview(changeset: dict, constraint_report: dict) -> str:
    lines = [f"GraphChangeSet {changeset['changeset_id']} — proposed changes:"]
    lines.append(f"  {len(changeset['proposed_nodes'])} node(s):")
    for node in changeset["proposed_nodes"]:
        lines.append(f"    + ({node['type']}) {node['node_id']}")
    lines.append(f"  {len(changeset['proposed_relationships'])} relationship(s):")
    for rel in changeset["proposed_relationships"]:
        lines.append(f"    + [{rel['type']}] {rel['from_node_id']} -> {rel['to_node_id']}")
    lines.append("")
    lines.append(f"ConstraintReport overall_status: {constraint_report['overall_status'].upper()}")
    for rule in constraint_report["rules"]:
        lines.append(f"  [{rule['status'].upper():^4}] {rule['rule_name']}: {rule['message']}")
    return "\n".join(lines)


class GraphApprovalSession:
    def __init__(self) -> None:
        self._previewed_changeset_ids: set[str] = set()

    def preview(self, changeset_id: str, *, session) -> str:
        """Calls the real §5.6 endpoint handler and renders the result."""
        from compliance_graph.src.db.changeset_repository import ChangesetRepository

        constraint_report = validate_changeset_handler(changeset_id, session=session)
        changeset = ChangesetRepository(session).get(changeset_id)
        self._previewed_changeset_ids.add(changeset_id)
        return render_graph_diff_preview(changeset, constraint_report)

    def guard_approval(self, changeset_id: str) -> None:
        if changeset_id not in self._previewed_changeset_ids:
            raise ApprovalWithoutPreviewError(
                f"Changeset {changeset_id} must be previewed (§5.6 validate) in "
                "this session before approval can be enabled."
            )
